# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$battery\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
read_only = " "

[battery]
full_symbol = "•"
charging_symbol = "⇡"
discharging_symbol = "⇣"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](bright-black) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

# # # Get editor completions based on the config schema
# # "$schema" = 'https://starship.rs/config-schema.json'
# #
# # # Theme defined later in the config
# # palette = "catppuccin_macchiato"
# #
# # # Prompt contents
# # format = """
# # [╭](fg:separator)\
# # $status\
# # $directory\
# # $git_branch\
# # $git_status\
# # $fill\
# # $python\
# # $lua\
# # $nodejs\
# # $golang\
# # $haskell\
# # $rust\
# # $ruby\
# # $aws\
# # $docker_context\
# # $jobs\
# # $cmd_duration\
# # $line_break\
# # $line_break\
# # [╰](fg:separator)\
# # $character\
# # """
# #
# # [character]
# # success_symbol = "[[󰄛](green) ❯](peach)"
# # error_symbol = "[[󰄛](red) ❯](peach)"
# # vimcmd_symbol = "[󰄛 ❮](subtext1)" # For use with zsh-vi-mode
# #
# # [os]
# # disabled = false
# # style = "fg:white"
# #
# # [os.symbols]
# # Windows = "  "
# # Ubuntu = "󰕈  "
# # Macos = "󰀵  "
# # Linux = "󰌽 "
# # Arch = "󰣇  "
# #
# # [directory]
# # truncation_length = 4
# # style = "bold lavender"
# # format = "[$path ]($style)"
# # truncation_symbol = "…/"
# # truncate_to_repo = false
# # read_only = " 󰌾"
# #
# # [git_branch]
# # style = "bold mauve"
# # symbol = ' '
# # format = '[on](white) [$symbol$branch ]($style)'
# #
# # [git_status]
# # style = 'fg:red'
# # format = '([$all_status$ahead_behind]($style) )'
# #
# # [git_commit]
# # tag_symbol = "  "
# #
# # [fill]
# # symbol = " "
# #
# # [jobs]
# # symbol = " "
# # style = "red"
# # number_threshold = 1
# # format = "[$symbol]($style)"
# #
# # [cmd_duration]
# # min_time = 500
# # style = "fg:gray"
# # format = "[$duration]($style)"
# #
# # [palettes.catppuccin_macchiato]
# # rosewater = "#f4dbd6"
# # flamingo = "#f0c6c6"
# # pink = "#f5bde6"
# # mauve = "#c6a0f6"
# # red = "#ed8796"
# # maroon = "#ee99a0"
# # peach = "#f5a97f"
# # yellow = "#eed49f"
# # green = "#a6da95"
# # teal = "#8bd5ca"
# # sky = "#91d7e3"
# # sapphire = "#7dc4e4"
# # blue = "#8aadf4"
# # lavender = "#b7bdf8"
# # text = "#cad3f5"
# # subtext1 = "#b8c0e0"
# # subtext0 = "#a5adcb"
# # overlay2 = "#939ab7"
# # overlay1 = "#8087a2"
# # overlay0 = "#6e738d"
# # surface2 = "#5b6078"
# # surface1 = "#494d64"
# # surface0 = "#363a4f"
# # base = "#24273a"
# # mantle = "#1e2030"
# # crust = "#181926"
# #
# #
# #
# # # =================================================================
# #
# # [aws]
# # symbol = " "
# # style = "yellow"
# # # format = "[$symbol($profile )(\[$duration\] )]($style)"
# # format = '[$symbol($profile )[$duration] ]($style)'
# #
# # [buf]
# # symbol = " "
# #
# # [bun]
# # symbol = " "
# #
# # [c]
# # symbol = " "
# #
# # [cpp]
# # symbol = " "
# #
# # [cmake]
# # symbol = " "
# #
# # [conda]
# # symbol = " "
# #
# # [crystal]
# # symbol = " "
# #
# # [dart]
# # symbol = " "
# #
# # [deno]
# # symbol = " "
# #
# # [docker_context]
# # symbol = " "
# # style = "fg:#06969A"
# # format = "[$symbol]($style) $path"
# # detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
# # detect_extensions = ["Dockerfile"]
# #
# # [elixir]
# # symbol = " "
# #
# # [elm]
# # symbol = " "
# #
# # [fennel]
# # symbol = " "
# #
# # [fossil_branch]
# # symbol = " "
# #
# # [gcloud]
# # symbol = "  "
# #
# # [golang]
# # symbol = " "
# #
# # [guix_shell]
# # symbol = " "
# #
# # [haskell]
# # symbol = " "
# #
# # [haxe]
# # symbol = " "
# #
# # [hg_branch]
# # symbol = " "
# #
# # [hostname]
# # ssh_symbol = " "
# #
# # [java]
# # symbol = " "
# #
# # [julia]
# # symbol = " "
# #
# # [kotlin]
# # symbol = " "
# #
# # [lua]
# # format = "[$symbol($version )]($style)"
# # symbol = " "
# #
# # [memory_usage]
# # symbol = "󰍛 "
# #
# # [meson]
# # symbol = "󰔷 "
# #
# # [nim]
# # symbol = "󰆥 "
# #
# # [nix_shell]
# # symbol = " "
# #
# # [nodejs]
# # symbol = " "
# #
# # [ocaml]
# # symbol = " "
# #
# # [package]
# # symbol = "󰏗 "
# #
# # [perl]
# # symbol = " "
# #
# # [php]
# # symbol = " "
# #
# # [pijul_channel]
# # symbol = " "
# #
# # [pixi]
# # symbol = "󰏗 "
# #
# # [python]
# # style = "teal"
# # symbol = " "
# # # format = "[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)"
# # format = "[${symbol}${pyenv_prefix}(${version} )($virtualenv )]($style)"
# # pyenv_version_name = true
# # pyenv_prefix = ""   # optional: removes prefix like "pyenv "
# #
# # [rlang]
# # symbol = "󰟔 "
# #
# # [ruby]
# # symbol = " "
# #
# # [rust]
# # symbol = "󱘗 "
# #
# # [scala]
# # symbol = " "
# #
# # [swift]
# # symbol = " "
# #
# # [zig]
# # symbol = " "
# #
# # [gradle]
# # symbol = " "
